---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: nginx-example
  labels:
    app: nginx-example
  annotations:
    openshift.io/display-name: nginx-example
spec:
  lookupPolicy:
    local: true
