---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nginx-example

configMapGenerator:
  - name: nginx-cm-pages
    files:
      - config/page4.html
    options:
      disableNameSuffixHash: true

resources:
  - ns-nginx-example.yaml
  - deployment-nginx.yaml
  - svc-nginx.yaml
  - route-server.yaml
  - pvc-nginx-pages.yaml

# Using Build Config
  - bc-nginx-example.yaml
  - is-nginx-example.yaml

# patches:
#   - target:
#       kind: Deployment
#       name: nginx  # Name of the deployment you want to patch
#     patch: |  # Inline patch
#       apiVersion: apps/v1
#       kind: Deployment
#       metadata:
#         name: nginx
#       spec:
#         template:
#           spec:
#             containers:
#               - name: nginx
#                 image: nginx-example:latest  # Change to use the ImageStreamTag
